AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: true

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 100